### ISSUE TITLE
composer.json has broken framework version constraint

### ISSUE THREAD

**Issue by oddnoc** [silverstripe-labs/silverstripe-sitetreeimporter#6]
Regardless of the framework version in a project, composer fails to resolve the constraint as stated:

      Problem 1
        - Installation request for silverstripe/sitetreeimporter * -> satisfiable by silverstripe/sitetreeimporter[dev-master].
        - silverstripe/sitetreeimporter dev-master requires silverstripe/framework 2.4,~3.0 -> no matching package found.

I had to make a separate branch for 2.4.x compatibility in my fork.

**Comment by dhensby** [comment]
Is this still a problem?

**Comment by oddnoc** [comment]
Probably not, although I'm actually on a project now where we need to upgrade a site from 2.2.2 to 2.4.13 because of severely deferred maintenance. Thanks for checking up on it, though!

**Comment by dhensby** [comment]
2.4 is EOL and no security releases - I would advise upgrading to 3.2 for some critical vulnerability patches.
